import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { BoxContainer } from '@/components/domains/index'
// 型定義
import type { VFC } from 'react'
import { GetStaticProps } from 'next'

type Item = {
  href: string
  title: string
  description: string
}

type Items = Item[]

type PropsType = {
  items: Items
}

const Home: VFC<PropsType> = ({ items }) => {
  return (
    <div className='flex flex-col justify-center items-center py-2 min-h-screen'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='flex flex-col flex-1 justify-center items-center px-20 w-full text-center'>
        <h1 className='text-6xl font-bold my-9'>
          Welcome to{` `}
          <a className='text-blue-600' href='https://nextjs.org'>
            Next.js!
          </a>
        </h1>

        <p className='mt-3 text-2xl'>
          Get started by editing {` `}
          <code className='p-3 font-mono text-lg bg-gray-100 rounded-md'>pages/index.tsx</code>
        </p>

        <div className='flex flex-wrap justify-around items-center mt-6 max-w-4xl sm:w-full'>
          {items.map((item) => {
            return <BoxContainer href={item.href} title={item.title} description={item.description} />
          })}
        </div>
      </main>

      <footer className='flex justify-center items-center mt-5 w-full h-24 border-t'>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
        </a>
      </footer>
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps<PropsType> = async () => {
  return {
    props: {
      items: [
        {
          href: 'https://nextjs.org/docs',
          title: 'LearnDeploy333 →',
          description: 'Find in-depth information about Next.js features and API',
        },
        {
          href: 'https://nextjs.org/learn',
          title: 'Learn →',
          description: 'Learn about Next.js in an interactive course with quizzes!',
        },
        {
          href: 'https://github.com/vercel/next.js/tree/canary/examples',
          title: 'Examples →',
          description: 'Discover and deploy boilerplate example Next.js projects.',
        },
        {
          href: 'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
          title: 'LearnDeploy →',
          description: 'Instantly deploy your Next.js site to a public URL with Vercel.',
        },
      ],
    },
  }
}
